name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
      - name: https://github.com/andreyb622/nestJs
        uses: elgohr/Publish-Docker-Github-Action@master
          with:
            registry: docker.pkg.github.com
            name: docker.pkg.github.com/andreyb622/nestJs/top-api-demo
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "develop1"